// Generated by BUCKLESCRIPT VERSION 4.0.18, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var ReasonReact = require("reason-react/src/ReasonReact.js");

var component = ReasonReact.statelessComponent("DocumentTitle");

function make(children) {
  return ReasonReact.wrapJsForReason(React.Fragment, { }, children);
}

var Fragment = /* module */[/* make */make];

function getTitle(param) {
  return document.title;
}

var partial_arg = document;

function setTitle(param) {
  partial_arg.title = param;
  return /* () */0;
}

function unsetTitle(param) {
  return setTitle("");
}

function handleDidUpdate(title) {
  var match = title !== document.title;
  if (match) {
    return setTitle(title);
  } else {
    return /* () */0;
  }
}

function make$1(title, children) {
  return /* record */[
          /* debugName */component[/* debugName */0],
          /* reactClassInternal */component[/* reactClassInternal */1],
          /* handedOffState */component[/* handedOffState */2],
          /* willReceiveProps */component[/* willReceiveProps */3],
          /* didMount */(function (_self) {
              return setTitle(title);
            }),
          /* didUpdate */(function (_oldAndNewSelf) {
              return handleDidUpdate(title);
            }),
          /* willUnmount */(function (_self) {
              return setTitle("");
            }),
          /* willUpdate */component[/* willUpdate */7],
          /* shouldUpdate */component[/* shouldUpdate */8],
          /* render */(function (_self) {
              return ReasonReact.element(undefined, undefined, make(children));
            }),
          /* initialState */component[/* initialState */10],
          /* retainedProps */component[/* retainedProps */11],
          /* reducer */component[/* reducer */12],
          /* jsElementWrapped */component[/* jsElementWrapped */13]
        ];
}

exports.component = component;
exports.Fragment = Fragment;
exports.getTitle = getTitle;
exports.setTitle = setTitle;
exports.unsetTitle = unsetTitle;
exports.handleDidUpdate = handleDidUpdate;
exports.make = make$1;
/* component Not a pure module */
